apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: gitops-example
images:
- name: gitops-example
  newName: elisska/gitops-example
  newTag: f614dea9d2be54fd45418872aab39fb55a1e0c1b
